application:
  name: "2ndBrain"
  version: "0.1.0"
  size:
    width: 1400
    height: 800
  position:
    x: 100
    y: 50
  status_bar:
    sub_process:
      height: 20
      width: 200
  icon: "2ndbrain.png"
